live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#ffffff"

[colors.bright]
black = "#666666"
blue = "#7aa6da"
cyan = "#70c0b1"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e7c547"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#1d1f21"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#b294bb"
red = "#cc6666"
white = "#c5c8c6"
yellow = "#f0c674"

[colors.primary]
background = "#1d1f21"
bright_foreground = "#eaeaea"
dim_foreground = "#828482"
foreground = "#c5c8c6"

[colors.footer_bar]
foreground = "#181818"
background = "#d8d8d8"

#[colors.search."colors.footer_bar"]
#background = "#c5c8c6"
#foreground = "#1d1f21"

[colors.search.focused_match]
background = "#000000"
foreground = "#ffffff"

[colors.search.matches]
background = "#ffffff"
foreground = "#000000"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[font]
#AppelFontSmoothing = true
size = 11.0

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Regular"

[hints]
alphabet = "jfkdls;ahgurieowpq"

[scrolling]
history = 10000

[window]
decorations_theme_variant = "Dark"
opacity = 0.8
startup_mode = "Windowed"
